import type { Metadata } from "next";
import {Poppins} from "next/font/google"
import "./globals.css";
import { Suspense } from "react";
import Loader from "@/components/shared/Loader";



const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight:["100", "200" , "300" , "400" ,"500" ,"600" ,"700", "800" , "900"],
  variable: "--font-poppins",
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} font-poppins antialiased bg-black text-white`}
      >
        <Suspense fallback={<Loader/>}>{children}</Suspense>
        
      </body>
    </html>
  );
}
